export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
export const LOAD_CART = "LOAD_CART";
export const CHECKOUT = "CHECKOUT";
export const UPDATE_TOTAL_ITEMS = "UPDATE_TOTAL_ITEMS";
export const UPDATE_TOTAL_PRICE = "UPDATE_TOTAL_PRICE";

export const ADD_TO_CART_TOAST = "ADD_TO_CART_TOAST";
export const REMOVE_FROM_CART_TOAST = "REMOVE_FROM_CART_TOAST";
export const ADD_QUANTITY_TO_CART_TOAST = "ADD_QUANTITY_TO_CART_TOAST";
export const CLEAR_CART_TOAST = "CLEAR_CART_TOAST";
export const DELETE_CART_ITEM_TOAST = "DELETE_CART_ITEM_TOAST";
